<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #0f172a; font-size: 11px; }
        h1, h2, h3 { margin: 0; }
        .cover { border: 1px solid #cbd5e1; padding: 24px; margin-bottom: 20px; }
        .brand { color: #0e7490; font-weight: 700; letter-spacing: .4px; }
        .muted { color: #64748b; }
        .summary { margin-top: 18px; width: 100%; border-collapse: collapse; }
        .summary td { border-bottom: 1px solid #e2e8f0; padding: 7px; }
        .slip { border: 1px solid #cbd5e1; padding: 14px; margin-bottom: 14px; page-break-inside: avoid; }
        .slip h2 { font-size: 15px; color: #0e7490; }
        .grid { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .grid td { border-bottom: 1px solid #e2e8f0; padding: 6px; vertical-align: top; }
        .label { width: 28%; color: #64748b; font-size: 9px; text-transform: uppercase; }
        .value { font-weight: 600; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
<div class="cover">
    <div class="brand">NiCARE / Niger State Contributory Health Agency</div>
    <h1>Bulk Enrollment Slip</h1>
    <p class="muted">Generated {{ $generatedAt->format('d M Y H:i') }} by {{ $generatedBy->name ?? 'System' }}</p>
    <table class="summary">
        <tr><td>Total enrollees</td><td><strong>{{ $enrollees->count() }}</strong></td></tr>
        <tr><td>Benefactor filter</td><td>{{ $filters['benefactor_id'] ?? 'All' }}</td></tr>
        <tr><td>Facility/provider filter</td><td>{{ $filters['facility_id'] ?? $filters['provider_id'] ?? 'All' }}</td></tr>
        <tr><td>Approval status</td><td>{{ $filters['approval_status'] ?? 'All' }}</td></tr>
    </table>
</div>

@foreach($enrollees as $enrollee)
    <div class="slip">
        <h2>{{ $enrollee->full_name ?: 'N/A' }}</h2>
        <div class="muted">{{ $enrollee->enrollee_id }} | {{ $enrollee->phone ?: 'No phone' }}</div>
        <table class="grid">
            <tr><td class="label">NIN</td><td class="value">{{ $enrollee->nin ?: 'N/A' }}</td></tr>
            <tr><td class="label">Programme</td><td class="value">{{ $enrollee->insuranceProgramme->name ?? 'N/A' }}</td></tr>
            <tr><td class="label">Category / Plan</td><td class="value">{{ $enrollee->enrolleeCategory->name ?? 'N/A' }} / {{ $enrollee->premiumPlan->name ?? 'N/A' }}</td></tr>
            <tr><td class="label">Funding</td><td class="value">{{ $enrollee->fundingType->name ?? 'N/A' }} / {{ $enrollee->benefactor->name ?? 'N/A' }}</td></tr>
            <tr><td class="label">Phase</td><td class="value">{{ $enrollee->enrollmentPhase->name ?? 'N/A' }}</td></tr>
            <tr><td class="label">Facility</td><td class="value">{{ $enrollee->facility->name ?? 'N/A' }} ({{ $enrollee->facility->hcp_code ?? 'N/A' }})</td></tr>
            <tr><td class="label">Location</td><td class="value">{{ $enrollee->lga->name ?? 'N/A' }} / {{ $enrollee->ward->name ?? 'N/A' }}</td></tr>
            <tr><td class="label">Coverage</td><td class="value">{{ optional($enrollee->coverage_start_date)->format('d M Y') ?: 'Pending' }} - {{ $enrollee->coverage_end_date ? $enrollee->coverage_end_date->format('d M Y') : 'No Expiry' }}</td></tr>
            <tr><td class="label">Status / Approval</td><td class="value">{{ $enrollee->status_label ?? $enrollee->status }} / {{ optional($enrollee->approval_date)->format('d M Y') ?: 'Pending' }}</td></tr>
            <tr><td class="label">Generated by</td><td class="value">{{ $generatedBy->name ?? 'System' }}</td></tr>
        </table>
    </div>
@endforeach
</body>
</html>
