<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('invoices', function (Blueprint $table) {
           $table->id();
           $table->string('reference', 50); 
           $table->string('invoice_number', 50)->nullable(); // order id to be generated
           $table->string('description')->nullable();
           $table->decimal('amount', 10, 2)->nullable();
           $table->string('invoice_type', )->default('cr'); // Cr=Credit Or Dr=Debit
           $table->date('payment_date')->nullable();
           $table->morphs('payable'); // e.g PremiumType, CapitationPayment
           $table->unsignedInteger('merchant_id');  // e.g Paystack Merchant, remita merchant
           $table->unsignedInteger('merchant_service_type_id'); // paystack sub account, remita service types etc
           $table->morphs('userable'); //generated by
           $table->json('metadata')->nullable(); // Additional data like ward
           $table->unsignedTinyInteger('status')->default(1);
           $table->unsignedSmallInteger('payment_catgory_id');
           $table->string('gateway_status')->nullable();
           
           $table->timestamps();

        });
    }

    public function down(): void
    {
        Schema::dropIfExists('premiums');
    }
};